# Generated by Django 4.1.6 on 2023-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_availableinvestment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableinvestment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/media/product/'),
        ),
    ]
