# Generated by Django 4.1.6 on 2023-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_availableinvestment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableinvestment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
