# Generated by Django 4.1.6 on 2023-09-08 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0004_alter_availableinvestment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableinvestment',
            old_name='investment',
            new_name='investment_duration_in_days',
        ),
        migrations.RemoveField(
            model_name='availableinvestment',
            name='investment_duration',
        ),
        migrations.RemoveField(
            model_name='availableinvestment',
            name='investors',
        ),
        migrations.CreateModel(
            name='ActiveInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=225, null=True)),
                ('expected_date', models.DateField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.availableinvestment')),
            ],
        ),
    ]
