# Generated by Django 4.1.6 on 2023-09-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_acct_no_user_created_at_user_image_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
