# Generated by Django 4.1.6 on 2023-09-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profit_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acct_no',
        ),
    ]
